#!/bin/bash

# Make temporary folder
rm -rf .doc_tmp
mkdir .doc_tmp
cd .doc_tmp

# initialize git repository
git init

# add remote
git remote add origin git@github.com:stefan-k/ARTBOX.git

# checkout gh-pages
git checkout -b gh-pages

# Pull everything
git pull origin gh-pages

# delete old documentation
rm -rf *

# copy documentation
cp -r ../doc/build/html/* .
touch .nojekyll

# add and commit all
git add -f --all .
git add -f --all .nojekyll
git commit -m 'Semiautomatic update of documentation'

# push
git push -f origin gh-pages

# remove temporary directory
cd ..
rm -rf .doc_tmp
